<?php

/**
 * @file
 * Hello World module file.
 */

use Drupal\Core\Routing\RouteMatchInterface;
/**
 * Implements hook_help().
 */
function music_search_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.music_search':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('About the music search module.') . '</p>';
      return $output;

    default:
  }
  return '';
}
/**
 * Implements hook_theme().
 */
function music_search_theme() {
  return [
    'music_search_results' => [
      'variables' => [
        'results' => [],
      ],
    ],
    'music_search_item_detail' => [
      'variables' => [
        'details' => [],
      ],
    ],
    'entity_field_selector' => [
      'variables' => [
        'entity_type' => '',
        'details' => [],
      ],
    ],
  ];
}

