Discogs_lookup.settings:
  type: config_object
  label: 'Discogs Lookup Settings'
  mapping:
    api_key:
      type: string
      label: 'Discogs API Key'
      description: 'The API key used to authenticate requests to the Discogs API.'
